import type { Config } from "tailwindcss"

export default {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        // Material Design 3 tokens from Stitch
        primary: "#0059bb",
        "on-primary": "#ffffff",
        "primary-container": "#0070ea",
        "on-primary-container": "#fefcff",
        "primary-fixed": "#d8e2ff",
        "primary-fixed-dim": "#adc7ff",
        "on-primary-fixed": "#001a41",
        "on-primary-fixed-variant": "#004493",
        secondary: "#515f74",
        "on-secondary": "#ffffff",
        "secondary-container": "#d5e3fc",
        "on-secondary-container": "#57657a",
        "secondary-fixed": "#d5e3fc",
        "secondary-fixed-dim": "#b9c7df",
        "on-secondary-fixed": "#0d1c2e",
        "on-secondary-fixed-variant": "#3a485b",
        tertiary: "#006947",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#00855b",
        "on-tertiary-container": "#f5fff6",
        "tertiary-fixed": "#6ffbbe",
        "tertiary-fixed-dim": "#4edea3",
        "on-tertiary-fixed": "#002113",
        "on-tertiary-fixed-variant": "#005236",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        background: "#f7f9fb",
        "on-background": "#191c1e",
        surface: "#f7f9fb",
        "on-surface": "#191c1e",
        "surface-variant": "#e0e3e5",
        "on-surface-variant": "#414754",
        "surface-dim": "#d8dadc",
        "surface-bright": "#f7f9fb",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f2f4f6",
        "surface-container": "#eceef0",
        "surface-container-high": "#e6e8ea",
        "surface-container-highest": "#e0e3e5",
        "surface-tint": "#005bc0",
        outline: "#717786",
        "outline-variant": "#c1c6d7",
        "inverse-surface": "#2d3133",
        "inverse-on-surface": "#eff1f3",
        "inverse-primary": "#adc7ff",
        // Legacy aliases
        card: "#ffffff",
        "card-foreground": "#191c1e",
        muted: "#f2f4f6",
        "muted-foreground": "#414754",
        accent: "#f2f4f6",
        "accent-foreground": "#191c1e",
        border: "#c1c6d7",
        input: "#c1c6d7",
        ring: "#0059bb",
        success: "#006947",
        warning: "#ba1a1a",
        destructive: "#ba1a1a",
        "destructive-foreground": "#ffffff",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Inter", "sans-serif"],
        display: ["Inter", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [],
} satisfies Config
